### ISSUE TITLE
output dir

### ISSUE THREAD

**Issue by piranna** [bytenode/bytenode#150]
Add option to set output directory, instead of doing it at the same one of the original files.

**Comment by OsamaAbbas** [comment]
That is a nice feature. However, I don't have much time for implementing it right now. I started working on v2.x of bytenode two or three months ago, but I got busy with other stuff. When I resume working on it, I might add this feature.

Thank you for your interest.

**Comment by piranna** [comment]
> When I resume working on it, I might add this feature.

Great :-) Yes, I saw about the v2, but don't know what features are you implementing. Do you have a roadmap somewhere? Are ESM modules part of it? 🤞🏻

**Comment by OsamaAbbas** [comment]
> > When I resume working on it, I might add this feature.
> 
> Great :-) Yes, I saw about the v2, but don't know what features are you implementing. Do you have a roadmap somewhere? Are ESM modules part of it? 🤞🏻

No. ESM modules are still experimental when in comes to the `vm` module in Node.js (which is needed in order to generate the cached data, or the v8 bytecode). See [here](https://nodejs.org/api/vm.html#vm_class_vm_sourcetextmodule). Even when it becomes stable, I still need to figure out how to implement it somewhat like the CommonJS modules. Last time I looked into this I was horrified :) .
