### ISSUE TITLE
CLI works on Bash but not Windows powershell

### ISSUE THREAD

**Issue by dominusmars** [bytenode/bytenode#152]
Ive been having issues compiling a directory using the cli. I'm creating a compiling script that will format the package directory from the directory above it where the code is. 
so the format is something like this 

![image](https://user-images.githubusercontent.com/55813440/129466636-794b54c6-8ce9-4979-84f6-607be86f7c12.png)

the .js files are located under the app directory and are split into separate folders 

Bytenode is able to compile all the js files under the app dir with git bash but not windows PowerShell 

![image](https://user-images.githubusercontent.com/55813440/129466663-bfff6c5f-7560-419f-a06c-23fa984663ff.png)
As shown above, idk if this is a bytenode issue or an issue on my side. 
I need to be able to run the bytenode command from inside a js file. 

like this 

`const {exec} = require("shelljs")`
`exec("bytenode -c package/app/**/*.js"); `

unless the package has a better way of doing it.

**Comment by OsamaAbbas** [comment]
The `./**/*` pattern does not work in Windows shells. I don't use windows since ~2008, so I don't even know if there is something like `./**/*` in Windows.

The current v1.x version will not receive any new features. So I might enhance the directory functions (both as an input and as an output) in v2.x. My schedule is tight these days though, so I don't know when I will finish v2.x and release it.

**Comment by dominusmars** [comment]
> The `./**/*` pattern does not work in Windows shells. I don't use windows since ~2008, so I don't even know if there is something like `./**/*` in Windows.
> 
> The current v1.x version will not receive any new features. So I might enhance the directory functions (both as an input and as an output) in v2.x. My schedule is tight these days though, so I don't know when I will finish v2.x and release it.

I'm excited to see what comes next for this project
