### ISSUE TITLE
Electron is not detected

### ISSUE THREAD

**Issue by WHK102** [bytenode/bytenode#175]
When try compile source for electron says an error:

```bash
$ bytenode --electron --compile app.js
Error: Electron not installed
    at /usr/local/lib/node_modules/bytenode/lib/index.js:51:13
    at new Promise (<anonymous>)
    at compileElectronCode (/usr/local/lib/node_modules/bytenode/lib/index.js:46:10)
    at Object.compileFile (/usr/local/lib/node_modules/bytenode/lib/index.js:221:28)
    at /usr/local/lib/node_modules/bytenode/lib/cli.js:77:24
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/bytenode/lib/cli.js:69:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
$ npm list -g | grep -i electron
├── electron-forge@5.2.4
├── electron@17.2.0
$ which electron
/usr/local/bin/electron
$ which electron-forge
/usr/local/bin/electron-forge
$ node -v
v14.17.5
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by WHK102** [comment]
Have already installed electron using `npx create-electron-app app`:

```bash
$ cat package.json 
{
  "name": "app",
  "productName": "app",
  "version": "0.0.1",
  "description": "App",
  "main": "index.js",
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "echo \"No linting configured\""
  },
  "keywords": [],
  "author": {},
  "license": "MIT",
  "config": {
    "forge": {
      "packagerConfig": {},
      "makers": [
        {
          "name": "@electron-forge/maker-squirrel",
          "config": {
            "name": "app"
          }
        },
        {
          "name": "@electron-forge/maker-zip",
          "platforms": [
            "darwin"
          ]
        },
        {
          "name": "@electron-forge/maker-deb",
          "config": {}
        },
        {
          "name": "@electron-forge/maker-rpm",
          "config": {}
        }
      ]
    }
  },
  "dependencies": {
    "bytenode": "^1.3.4",
    "electron-squirrel-startup": "^1.0.0"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.63",
    "@electron-forge/maker-deb": "^6.0.0-beta.63",
    "@electron-forge/maker-rpm": "^6.0.0-beta.63",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.63",
    "@electron-forge/maker-zip": "^6.0.0-beta.63",
    "electron": "17.2.0"
  }
}
```

And binaries is already installed as global.

**Comment by OsamaAbbas** [comment]
I can reproduce the issue. Thanks for reporting.

The issue lies in this line:
https://github.com/bytenode/bytenode/blob/3a42649a61f17773e654caaee863e2f9680ca6d7/lib/index.js#L49

Apparently, this is not a reliable method for getting the `node_modules/electron/cli.js` file.

As a quick fix, I replaced that line with:
```JavaScript
const electronPath = require('electron').replace('dist/electron', 'cli.js');
```
and it works.

@jjeff Could you please make sure that my line won't break anything else? I believe this way is more reliable than trying to find `electron/cli.js` manually. Requiring 'electron' module would return the executable path or throw an error if it's missing, and from that executable path we can get the `cli.js` file. I'm not fully aware of the electron part logic, so if it seems good for you I will make the fix and publish it to npm.

@WHK102 Until we push an update, you can fix that line in your local bytenode copy (i.e. `YOUR_APP/node_modules/bytenode/lib/index.js`). But you will have to compile using this local copy itself, not the globally installed version.
So you will do something like this: `$ ./node_modules/.bin/bytenode --electron --compile app.js`. It should work and you will run your app using `npm run start` as usual.

**Comment by jjeff** [comment]
@OsamaAbbas I remember writing that `path.join()` line and thinking "There's about a 60% chance this will actually work for everyone." 🙂 So I'm not too surprised that it's a problem.

I tested your solution and it looks like it doesn't work on MacOS.

Here are two more robust solutions (which work on Mac):

```JS
// without path module
const electronPath = require.resolve('electron').replace('index.js', 'cli.js');

// with path module (slightly more robust)
const electronPath = path.join(path.dirname(require.resolve('electron')), 'cli.js');
```
