### ISSUE TITLE
error  inline  event define  

### ISSUE THREAD

**Issue by samantrader** [bytenode/bytenode#202]
Hi
if    define   inline  event   in  html  tag   so  ->

`   <div   onclick="callfunction()"  >test </div>`

(this   div  generate at  runtime  and  dono't  know its  ID )

and    callfunction  define  into  compiled    script  file   (with bytenode)   

when  click  on  div  this  error  was  showed  :     callfunction don't define   

how  work  with  this  situation ?

**Comment by samantrader** [comment]
this  html  code  in  electron

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello World!</title>
    <script defer src="render2.js"></script>
  </head>
  <body class="content">
    <button id="btn1" onclick="testfunc()">testclick</button>
  </body>
</html>
```

**Comment by OsamaAbbas** [comment]
Your code does not (and won't) work even without bytenode. Try it, it does not work.

You must export the function[s] that you want to use from the protected file, and then attach it to a context where HTML elements can reach.

A suggested edit would be:

```diff
// render.js, before compiling it to render.jsc

const ipcRenderer = require("electron").ipcRenderer;
const electron = require("electron");
const { BrowserWindow } = require("@electron/remote");
const { dialog, remote, Menu } = require("@electron/remote");

function testfunc() {

  console.log("test");
}

+ exports.testfunc = testfunc;
```

```diff
// render2.js
const bytenode = require("bytenode");
+ window.testfunc = require("./render.jsc").testfunc;
```

**Comment by samantrader** [comment]
Hi  
 My code  testfunc()  works    please  test  it   
This  address  is  simple full   source   please say me  how  use    bytenode   for  this  source  

[](https://github.com/samantrader/testbytenode)

**Comment by OsamaAbbas** [comment]
I just showed you how to do it!

Do you see these green lines? Add those lines to your code and recompile your file. It should work.

Of course if you added a plain javascript to the page directly, using the `<script src=""></script>` tag: any functions or variables will be attached to the window object. This is not the case when you `require` files (whether they are `.js` or `.jsc`). That's why you have to make these changes in order to attach your functions to the window object (which HTML elements have a direct access to its functions amd variables).

**Comment by OsamaAbbas** [comment]
What I meant by your code won't work even without bytenode: is exactly what I explained in the previous comment.

Just test this: in your `render2.js`, please require your original `render.js` file, not `render.jsc` file. It WON'T work, because the design itself is wrong.

If you want it to work, add the green lines in my comment.

**Comment by samantrader** [comment]
I   send for you a very simple  code    
the   render.js  is   main  page    render  js   file   and  can be   very  complex
you are  supposed  that  testfunc()   send   a  message  to   Ipcmain  

`
const ipcRenderer = require("electron").ipcRenderer;
const electron = require("electron");
const { BrowserWindow } = require("@electron/remote");
const { dialog, remote, Menu } = require("@electron/remote");

function testfunc() {
ipcRenderer.send("openchat", {});
//  console.log("test");
+ hhhhhhh
}`

**Comment by ngohuytrieu** [comment]
@samantrader technically you need to export your functions and then import them in order to use them in other files.

**Comment by OsamaAbbas** [comment]
A better approach will be to import the whole module and attach it to the window object once.

Like this:

```javascript
// render2.js

const bytenode = require("bytenode");

require("./render.jsc");

window.MY_API = require("./render.jsc");
```

Then, in your html:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello World!</title>
    <script defer src="render2.js"></script>
  </head>
  <body class="content">
    <button id="btn1" onclick="MY_API.testfunc()">testclick</button>
  </body>
</html>
```
