### ISSUE TITLE
Error:  cannot find module 'node:assert/strict'

### ISSUE THREAD

**Issue by rstupek** [bytenode/bytenode#220]
When trying to run bytenode, I am getting the above error in index.js 3:16.  I have upgraded to the latest nodejs and npm and that didn't seem to correct the issue.  Any idea what I might be doing wrong?

**Comment by jjeff** [comment]
I was just having this same problem today myself. All of my internet searches said, "update Node" and re-install your `node_modules` folder. But I tried those things and the latest Node (18.17.0) was still producing the error.

It seems like Node is interpreting "use strict" at the top of index.js as a module import.

Unfortunately, I don't have an answer. I ended up reworking my code and somehow things started working again.

Maybe @OsamaAbbas will have thoughts.

**Comment by OsamaAbbas** [comment]
I cannot reproduce the error in node 18.x nor in node 20.x (on my linux machine).

> It seems like Node is interpreting "use strict" at the top of index.js as a module import.

This is not the cause of the problem. The problematic module lies clearly in this line: https://github.com/bytenode/bytenode/blob/27b4c87a1e6f0825c91674552fd654cbef98657f/lib/index.js#L3

As I'm unable to reproduce the error, could you please change line 3 and 4 from:

```javascript
const { ok } = require('node:assert/strict');
const { brotliCompressSync, brotliDecompressSync } = require('node:zlib');
```

to

```javascript
const { ok } = require('assert/strict');
const { brotliCompressSync, brotliDecompressSync } = require('zlib');
```

and see if the error persists?

**Comment by OsamaAbbas** [comment]
Another possibility: do you use webpack or similar packaging solutions? This might be the cause. It seems that `require('node:MODULE')` syntax won't work unless the `require` function is the native node require function. If webpack (or similar solutions) defines its own `require` function, it might think that you want a library called `node:MODULE` from `node_modules` folder.

So, edit line 3 and 4 to require `assert/strict` and `zlib` instead of `node:assert/strict` and `node:zlib`. If this solves the issue, I will fix them and publish a new version right away.

**Comment by rstupek** [comment]
I don't think I'm using webpack.  I did previously try removing node: from the require however it just gave Error: Cannot find module 'assert/strict'.  I've tried v18 and v20 with the same error (I'm on windows).

**Comment by jjeff** [comment]
I was using Electron Forge too. 

FWIW, I'm creating a Bytenode plugin for Electron Forge, if that sounds interesting. I've got it working in my project, but I need to create a repository around it. Looking for collaborators.

**Comment by OsamaAbbas** [comment]
So it seems to be an issue with electron forge.

As I always say, I have little to none experience with (insert anything related to electron or web development), can you help me with a minimal setup that shows the issue?

**Comment by jjeff** [comment]
What version of Node is required to support the `node:`-prefixed require statements? I think that Electron Forge may be running Electron's version of Node instead of your current session's. Electron was running Node 16 up until Electron v22. Here's a [list that maps Electron to Node versions](https://www.electronjs.org/docs/latest/tutorial/electron-timelines). If Electron 16 does not support the `node:`-prefixes, this might be the problem.

Another theory: Electron Forge may be spawning sub-processes which, in turn, trigger its hooks. So if, for instance, you're using NVM to run a given version of Node, but you've got a different version of Node installed at the system level, the system-level Node may be triggering the error. I would assume that Node's subprocesses would inherit their parent's runtime environment… but maybe not? You could test this theory with a `console.log(process.version)` inside your hook to see what version of Node is running. You'll also probably want to do an `export DEBUG=*` to set the DEBUG env var and disable Listr in Electron Forge so you can see your console messages.

Sorry. Lots of theories. I don't have time to test right now. But this is where I'd start.

**Comment by clarkttfu** [comment]
I found it's about npx. 

Compiling on my Respberry Pi 4 (arm64 Debian 11), `npx bytenode -c` works with Node 18 installed from https://github.com/nodesource/distributions#using-debian-as-root-2.

But `npx bytenode -c` throws `node:assert/strict` if I used Node.js downloaded from https://nodejs.org/download/release/v14.21.3. 

And it compiled successfully (with Node 14 above) if I invoked bytecode with Node binary directly like:
`node $DIR/node_modules/bytenode/lib/cli.js -c xxx`

**Comment by OsamaAbbas** [comment]
I tried both `npx bytenode -c index.js` and `npx bytenode index.jsc`. Both worked with no errors on Node v18.17.0 and v20.5.0.

I can reproduce the error with Node v14.21.3, with and without npx.

So, I guess I figured out the reason. I will push a fix right now.
