### ISSUE TITLE
Protection against View8

### ISSUE THREAD

**Issue by ohnnnooo** [bytenode/bytenode#241]
With the release of View8 bytenode seems to have lost it's use for protection of source code. Is there any way we can still protect our code against View8 ?

https://github.com/suleram/View8

**Comment by j4k0xb** [comment]
> bytenode seems to have lost it's use for protection of source code

there was never any "protection" in the first place other than hoping someone would be too lazy to disassemble (guides existed for years: https://github.com/noelex/v8dasm)

> Is there any way we can still protect our code against View8 ?

no. v8 has to execute it which means it's impossible to hide

**Comment by OsamaAbbas** [comment]
I haven't checked out View8 yet, but I will copy an old private message I wrote, in relation to [this article](https://swarm.ptsecurity.com/how-we-bypassed-bytenode-and-decompiled-node-js-bytecode-in-ghidra):

> This is very interesting! In fact, I'm glad that someone went this far and tried to decompile bytenode.
> 
> I tried their plugin myself. What I found is that it does not undermine bytenode functionality, as their "decompiled" code is not the same as the original one. It's useful in analyzing the general picture to see if the bytecode contains malware parts in it, but there is no way to restore the original code.
> 
> Also, I managed to decompile only simple scripts. Once the code grows, their plugin cannot analyze nor decompile the compiled .jsc files. It is still doable if they fix their package though, which is not an easy task.
> 
> If we have script.js that has only this line:
> 
> `console.log('hi');`
> 
> Here is the decompiled version:
> 
> ![image](https://github.com/user-attachments/assets/405ff08c-770b-489c-b4e5-cd2f3fa43abe)
> 
> ![image](https://github.com/user-attachments/assets/6cd7e167-7c81-4c35-bfc2-2c772a2e4798)
> 
> I tried to decompile the [express example](https://github.com/bytenode/bytenode/blob/master/examples/express-hello-world/server.js), and it was decompiled into four functions:
> 
> ![image](https://github.com/user-attachments/assets/fa522e00-568d-43a8-906f-dbbca89ffb60)
> 
> Again, this is very useful if someone needs to analyze the .jsc file from a security perspective. Just like analyzing regular C or C++ compiled executable files.

In short, I believe it's important to have tools that can disassemble bytenode (or C, or C++, or any other language) from a security perspective.

If such tools can only reveal what the code does, then they don't undermine the value of bytenode. (This would be similar to the case mentioned in the aforementioned article).

But if such tools can restore the original source code, so that your competitors or users can just copy your work as is, then, yes, such tools render bytenode obsolete. (This would be similar to Java decompilers, where the decompiled version is almost identical to the original code).

**Comment by ohnnnooo** [comment]
@j4k0xb @OsamaAbbas 

yeah i understand it's impossible to hide like anything else but at least it was hard for just anybody to be able to decompile your whole application

View8 doesn't just disassemble to make it easy for someone to check for malware but seems to decompile the code to readable javascript if not almost original which only allows others to copy your whole code or just remove authentication on paid apps

**Comment by j4k0xb** [comment]
> But if such tools can restore the original source code

No tool can do that as of now, it's still like pseudo-code (but closer to js compared to the ghidra article)

> But if such tools can restore the original source code, so that your competitors or users can just copy your work as is, then, yes, such tools render bytenode obsolete. (This would be similar to Java decompilers, where the decompiled version is almost identical to the original code).

It should be possible to make a decompiler that outputs equivalent code you can just run
The serialized data also contains quite a bit more information which can help with restoring the coding style, in some cases even the variable/parameter names
